### ISSUE TITLE
'Clean / Obsolete Environments' dialog shows removed environments after first run

### ISSUE THREAD

**Issue by d-gs** [aposin/gem#35]
After the first cleanup of obsolete environments, when the dialog is opened again without closing GEM, the obsolete environments are still shown.

## Expected Behavior - What were you expecting to happen?

No already successfully removed obsolete environments present on the dialog.

## Current Behavior - What happens?

Removed environments are still shown (and kept on the cache of identified obsolete environments).

## Possible Solution

Handle properly the cache of obsolete environments, so when removed they are also removed from the cached list.

## What are the steps to reproduce this issue? (for bugs)

On a GEM state with obsolete environments:

1. Select the menu ' Clean' -> 'Obsolete Environments' 
2. Perform a clean of one or several obsolete environments
3. After the cleanup, close the progress popup
4. Select the menu ' Clean' -> 'Obsolete Environments' again
5. The list of obsolete environments still contains the removed one

## Your Environment

* Version used: Any > 0.3.0
* Operating System and version (desktop or mobile): Windows

**Comment by d-gs** [comment]
@irenejoeunpark - any progress on this? Or should we consider that it is open for other people to work on it?

**Comment by irenejoeunpark** [comment]
@d-gs Sorry I should have given you updates on it. I have been facing some environmental issues when setting up. Please assign this to someone else. Sorry for the late communication.
