### ISSUE TITLE
CommandProgressDialog does not scale with lots of commands

### ISSUE THREAD

**Issue by d-gs** [aposin/gem#36]
## Bug report

The `CommandProgressDialog` does not scale with lots of commands, cause the cli-like view is too small and the list goes out of the dialog range so the information is not visible to the user.

## Expected Behavior - What were you expecting to happen?

The progress dialog should be usable for cases with any number of commands to run.

## Current Behavior - What happens?

As the number of commands increase, little space is left for the actual information of the run command.

## Possible Solution

There are several solutions for this:

1. Scrollable composite for the part that shows all the commands cli-like view.
2. A different type of dialog (e.g., show the cli-like view on a different dialog if the user wants to see it), either for all cases or for the ones with more than X number of commands to run.

## What are the steps to reproduce this issue? (for bugs)

On a GEM state with a lot of obsolete environments:

1. Select the menu ' Clean' -> 'Obsolete Environments'
2. Perform a clean of all the obsolete environments
3. The progress dialog is not showing anything on the cli-like views and some of the removed environments is not even shown.

## Context

This will happen with lots of obsolete environments as in the steps for reproduction, but also in the case of a configured environment with lots of repositories.

## Your Environment

* Version used: > 0.3.0
* Operating System and version (desktop or mobile): Windows

**Comment by davu-all** [comment]
Another option would be keep a single cli-like view with tabs (one for each running process) where pressing on a tab switches the content of the cli-like view shows the logs for the selected process.
